services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"  # Web UI 访问
      - "8020:8020"  # RPC 访问
    volumes:
      - ./namenode_data:/hadoop/dfs/name
      # - ../db-generation/articles:/articles
      - /Users/ckh/TsingHua清华/Phd/Sem1/DistributedDatabaseSystems/Assignment/project/code/db-generation/articles:/articles
      - ./4_hadoop_setup.sh:/setup.sh
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=2
    deploy:
      resources:
        limits:
          cpus: '4'  # 设置CPU限制为4核
        reservations:
          cpus: '2'  # 设置CPU保留为2核
    networks:
      - hadoop_cluster_net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    ports:
      - 9864:9864 # DataNode1 Web UI
    volumes:
      - datanode1_data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    networks:
      - hadoop_cluster_net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    ports:
      - 9865:9864 # DataNode1 Web UI
    volumes:
      - datanode2_data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    networks:
      - hadoop_cluster_net
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    volumes:
      - datanode3_data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_datanode_handler_count=30
      - HDFS_LOGLEVEL=WARN
    ports:
      - 9866:9864 # DataNode1 Web UI
    depends_on:
      - namenode
    networks:
      - hadoop_cluster_net
  # resourcemanager:
  #   image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
  #   container_name: resourcemanager
  #   environment:
  #     - SERVICE_PRECONDITION=namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864
  #     - HDFS_LOGLEVEL=WARN
  #   networks:
  #     - hadoop
  #   ports:
  #     - "8088:8088" # Web UI for ResourceManager
  # monitoring:
  #   image: inseefrlab/hadoop-prometheus-collector
  #   container_name: hadoop-monitoring
  #   depends_on:
  #     - namenode
  #     - datanode1
  #     - datanode2
  #   ports:
  #     - 8080:8080 # Prometheus monitoring service
  #   environment:
  #     - NAMENODE_HOST=namenode
  #     - NAMENODE_PORT=9870
  #     - DATANODE_HOSTS=datanode1,datanode2,datanode3
  #   networks:
  #     - hadoop
volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
  datanode3_data:

networks:
  hadoop_cluster_net:
    external: true