
services:
  mongodb_exporter_router:
    image: percona/mongodb_exporter:0.42.0
    container_name: mongodb_exporter_router
    command:
      - --mongodb.uri=mongodb://router:27017
      - --collect-all
      - --compatible-mode
      - --split-cluster
      # - --mongodb.collstats-colls=config.App,config.ApplicationOverride,config.Caller,config.CommonRules,config.HabilitationOverride,config.IconSvg,config.UpdateStatusEntity,config.feature
    networks:
      - mongo_cluster_net
      - prometheus_net
    ports:
      - "9216:9216" 
    restart: always

  mongodb_exporter_configsvr:
    image: percona/mongodb_exporter:0.42.0
    container_name: mongodb_exporter_configsvr
    command:
      - --mongodb.uri=mongodb://configsvr_a:27017,configsvr_b:27017,configsvr_c:27017
      - --collect-all
      - --compatible-mode
      - --split-cluster
    networks:
      - mongo_cluster_net
      - prometheus_net
    ports:
      - "9217:9216" 
    restart: always
  mongodb_exporter_dbms1:
    image: percona/mongodb_exporter:0.42.0
    container_name: mongodb_exporter_dbms1
    command:
      - --mongodb.uri=mongodb://dbms1_a:27017,dbms1_b:27017
      - --collect-all
      - --compatible-mode
      - --split-cluster
    networks:
      - mongo_cluster_net
      - prometheus_net
    ports:
      - "9218:9216" 
    restart: always
  mongodb_exporter_dbms2:
    image: percona/mongodb_exporter:0.42.0
    container_name: mongodb_exporter_dbms2
    command:
      - --mongodb.uri=mongodb://dbms2_a:27017,dbms2_b:27017
      - --collect-all
      - --compatible-mode
      - --split-cluster
    networks:
      - mongo_cluster_net
      - prometheus_net
    ports:
      - "9219:9216" 
    restart: always
  
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    # depends_on:
    #   - redis
    networks:
      - redis_net
      - prometheus_net

  hadoop_exporter:
    image: marcelmay/hadoop-hdfs-fsimage-exporter
    container_name: hadoop_exporter
    ports:
      - "9709:9709"
    volumes:
      - ./namenode_data:/fsimage-location
    environment:
      - JAVA_OPTS=-server -XX:+UseG1GC -Xmx1024m
    # depends_on:
    #   - namenode
    networks:
      - hadoop_cluster_net
      - prometheus_net

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    volumes:
      - ./6_prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus_net
    ports:
      - "9090:9090"
    restart: always
    
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    networks:
      - prometheus_net
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning 
      - ./grafana/dashboards_template:/var/lib/grafana/dashboards
    restart: always

networks:
  mongo_cluster_net:
    external: true
  hadoop_cluster_net:
    external: true
  prometheus_net:
    driver: bridge