{
 "title": "Opstree/Mongodb Dashboard",
 "description": "MongoDB Dashboard with Cluster, Replication, cursor, and server metrics using Mongodb Exporter by percona",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "env", "query": { "query": "label_values(mongodb_up, env)" } },
   {
    "name": "mongoJob",
    "query": {
     "query": "label_values(mongodb_up{env=\"$env\"}, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up{env=\"$env\"}, instance)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeJob",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mountpoints",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, mountpoint)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_disk_reads_completed_total, device)"
    }
   },
   {
    "name": "rs",
    "label": "ReplicaSet",
    "query": {
     "query": "label_values(mongodb_rs_ok{env=\"$env\"}, rs_nm)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Total Collections/DB",
   "type": "gauge",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " mongodb_mongod_db_objects_total{env=\"$env\", instance=\"router\"}",
     "legendFormat": "{{database}}"
    },
    {
     "expr": " mongodb_mongod_db_objects_total{env=\"$env\", instance=\"dbms1\"}",
     "legendFormat": "{{database}}"
    },
    {
     "expr": " mongodb_mongod_db_objects_total{env=\"$env\", instance=\"dbms2\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "MongoService UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mongodb Uptime",
   "type": "stat",
   "description": "Mongodb Service Uptime in hours",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_members_uptime{env=~\"$env\", member_state=\"PRIMARY\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"current\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Created Connections",
   "type": "stat",
   "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"totalCreated\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "opcounters",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "A document that reports on database operations by type since the mongod instance last started. These numbers will grow over time until next restart. Analyze these values over time to track database utilization."
   }
  },
  {
   "title": "Received Insert Operations",
   "type": "timeseries",
   "description": "The total number of insert operations received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"$env\", legacy_op_type=\"insert\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Update Operations",
   "type": "timeseries",
   "description": "The total number of update operations received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"$env\", legacy_op_type=\"update\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Command Operations",
   "type": "timeseries",
   "description": "The total number of commands issued to the database since the mongod instance last started.\n\nopcounters.command counts all commands except the write commands: insert, update, and delete.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"$env\", legacy_op_type=\"command\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Queries",
   "type": "timeseries",
   "description": "The total number of queries received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"$env\", legacy_op_type=\"query\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Delete Operations",
   "type": "timeseries",
   "description": "The total number of delete operations since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"$env\", legacy_op_type=\"delete\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received getMore Operations",
   "type": "timeseries",
   "description": "The total number of getMore operations since the mongod instance last started. This counter can be high even if the query count is low. Secondary nodes send getMore operations as part of the replication process.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"$env\", legacy_op_type=\"getmore\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Collections/DB",
   "type": "state-timeline",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "mongodb_dbstats_collections{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Indexs/DB",
   "type": "state-timeline",
   "description": "Total number of indexes across all collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexes{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Views/DB",
   "type": "state-timeline",
   "description": "Number of views in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "mongodb_dbstats_views{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Allocated Storage to Collections in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_storageSize{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{database}} "
    }
   ]
  },
  {
   "title": "Allocated Storage to Indexs in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all indexes in the database, including free index space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexSize{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Replication Set Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_id{env=\"$env\", member_state=\"PRIMARY\", instance=\"$instance\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time - $instance",
   "type": "timeseries",
   "description": "This metric can show a correlation with the replication lag value.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_rs_members_pingMs{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "OPLog Size",
   "type": "timeseries",
   "description": "The oplog (operations log) is a special capped collection that keeps a rolling record of all operations that modify the data stored in your databases.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_oplog_stats_size{env=\"$env\", instance=\"$instance\", rs_nm=\"$rs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_id{env=\"$env\", member_state=\"SECONDARY\", instance=\"$instance\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "MongoDB replication lag occurs when the secondary node cannot replicate data fast enough to keep up with the rate that data is being written to the primary node. It could be caused by something as simple as network latency, packet loss within your network, or a routing issue.",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_rs_members_optimeDate{env=\"$env\", instance=\"$instance\", rs_nm=\"$rs\"} - mongodb_rs_members_optimeDate{env=\"$env\", instance=\"$instance\", rs_nm=\"$rs\"}",
     "legendFormat": "{{member_state}}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_electionCandidateMetrics_lastElectionDate{env=\"$env\"}"
    }
   ]
  },
  { "title": "Cursor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Cursor Timeout",
   "type": "timeseries",
   "description": "Cursor is a pointer, and using this pointer we can access the document. cursor.timeOut property was updated incrementally, and connections that died without closing the cursor. The consequence is that it will remain open on the server and consume memory unless it is reaped by the default MongoDB setting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_cursor_timedOut{env=\"$env\", rs_nm=\"$rs\"}",
     "legendFormat": "{{instance}} - {{rs_nm}}"
    }
   ]
  },
  {
   "title": "Cursor totalOpened",
   "type": "timeseries",
   "description": "Number of cursors currently opened by MongoDB for clients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_cursor_totalOpened{env=\"$env\", rs_nm=\"$rs\"}",
     "legendFormat": "{{instance}} - {{rs_nm}}"
    }
   ]
  },
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{env=\"$env\", mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{env=\"$env\", job=\"$nodeJob\"} - node_memory_MemFree_bytes{env=\"$env\", job=\"$nodeJob\"} - (node_memory_Cached_bytes{env=\"$env\", job=\"$nodeJob\"} + node_memory_Buffers_bytes{env=\"$env\", job=\"$nodeJob\"})",
     "legendFormat": "{{instance}} - RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{env=\"$env\", job=\"$nodeJob\"} + node_memory_Buffers_bytes{env=\"$env\", job=\"$nodeJob\"} + node_memory_SReclaimable_bytes{env=\"$env\", job=\"$nodeJob\"}",
     "legendFormat": "{{instance}} - Buffer Mem"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{env=\"$env\", job=\"$nodeJob\"}[5m])",
     "legendFormat": "{{instance}}-{{device}} - Receives"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{env=\"$env\", job=\"$nodeJob\"}[5m])",
     "legendFormat": "{{instance}}-{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{env=\"$env\", job=\"$nodeJob\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{instance}}-{{device}} - Reads"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{env=\"$env\", job=\"$nodeJob\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{instance}}-{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{env=\"$env\", job=\"$nodeJob\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{env=\"$env\", job=\"$nodeJob\",device!~'rootfs'})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}